
name: Run Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create credentials
      run: |
        echo '${{ secrets.GOOGLE_SERVICES }}' > ./composeApp/google-services.json
        echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties
        
    - name: Remove build cache directory
      run: rm -rf ./build-cache

    - name: Run tests
      run: ./gradlew cleanTestDebugUnitTest testDebugUnitTest --no-build-cache --rerun-tasks
      env:
        GRADLE_OPTS: "-Dorg.gradle.caching=false"
